apiVersion: v1
kind: Service
metadata:
  name: my-nginx-react
  labels:
    run: my-nginx-react
spec:
  type: NodePort
  ports:
  - nodePort: 32210
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    run: my-nginx-react


