apiVersion: v1
kind: Service
metadata:
  name: demo-javareact
  labels:
    run: demo-javareact
spec:
  type: NodePort
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: demo-javareact


